FROM debian 
SHELL ["/bin/bash", "-c"]

RUN     echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
        && apt-get update \
        && apt-get upgrade -y \
        && apt-get install -y wget ca-certificates curl

RUN     wget https://github.com/WyvernTKC/cpuminer-gr-avx2/releases/download/1.2.4.1/cpuminer-gr-1.2.4.1-x86_64_linux.tar.gz -O - | tar xvz -C /opt \
        && wget https://raw.githubusercontent.com/fantacinni/cpuminer/main/i7-6700/tune_config -O $(find /opt -name cpuminer.sh -printf '%h\n')/tune_config \
        && wget https://raw.githubusercontent.com/fantacinni/cpuminer/main/i7-6700/config.json -O $(find /opt -name cpuminer.sh -printf '%h\n')/config.json

CMD     cd $(find /opt -name cpuminer.sh -printf '%h\n') && ./cpuminer.sh
